name: Build Docs

on:
  push:
    branches:
      - main
      - release/*
    tags:
      - v[0-9]+.[0-9]+.[0-9]
      - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+
  pull_request:
  workflow_dispatch:

concurrency:
  group: build-docs-${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l -eo pipefail {0}

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: csl/test1

      - name: Move and commit changes
        env:
          GITHUB_PYTORCHBOT_TOKEN: ${{ secrets.CATS_TOKEN }}
        run: |
          set -euox pipefail
          git remote set-url origin https://clee2000:${GITHUB_PYTORCHBOT_TOKEN}@github.com/pytorch/torchtune.git
          git remote -v
          git config user.name "clee2000"
          git config user.email "csl@meta.com"
          echo 'yet another line' >> data.txt
          git add .
          git commit -m "update"
          git push origin csl/test1
